name: Android CI(Scene5)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: master

    - name: Setup NDK r23b
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r23b
        add-to-path: true

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleRelease
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: scene-dev
        path: ${{ github.workspace }}/app/build/outputs/apk/release/*.apk
        if-no-files-found: warn
